### ISSUE TITLE
mockeryMapper type error

### ISSUE THREAD

**Issue by lizyChy0329** [Saeris/valimock#41]
Type '(options?: { width?: number | undefined; height?: number | undefined; } | undefined) => string' is not assignable to type 'FakerFunction'.

TypeScript: 5.5.4

```ts
import type { FakerFunction } from 'valimock'
import * as v from 'valibot'
import { Valimock } from 'valimock'

export const ImageListSchema = v.array(v.object({
  imageFileUri: v.string(),
  imageVsCodePath: v.string(),
  basename: v.string(),
  extname: v.string(),
}))

export type ImageListData = v.InferOutput<typeof ImageListSchema>

export const imageListMock = new Valimock({
  mockeryMapper: (key, faker) => {
    // if (typeof key === 'string' && key === 'imageVsCodePath') {
    //   return () => 'https://loremflickr.com/640/480?lock=1234'
    // }
    const keyToFnMap: Record<string, FakerFunction> = {
      image: faker.image.url,
      imageurl: faker.image.url,
      imageVsCodePath: faker.image.url,
      number: faker.number.int,
      float: faker.number.float,
      hexadecimal: faker.number.hex,
      uuid: faker.string.uuid,
      boolean: faker.datatype.boolean,
      city: faker.location.city,
    }

    if (typeof key === `string` && key.toLowerCase() in keyToFnMap) {
      return keyToFnMap[key.toLowerCase()]
    }
  },
}).mock(ImageListSchema)
```

![image](https://github.com/user-attachments/assets/1b540269-7c16-43c3-8db9-dcad4fd0bb02)

**Comment by Saeris** [comment]
Hey thanks for the report @lizyChy0329! I haven't updated Valimock since before Typescript 5.5 was released so that in possible combination of new versions of Valibot may be the source of this type error.

Presently I am unable to make any updates to this library as I am on sabbatical attending language school right now, which leaves me with very little time to write code. If you would like to try and take a stab at updating Valimock to have compatibility with TypeScript 5.5 I would greatly appreciate a PR!

As indicated in #40 I do want to do a comprehensive upgrade of Valimock once Valibot has a stable 1.0 release. At this time it is still at a beta release candidate. So unfortunately that may mean that at this time Valimock may not work in your project and I apologize for that.

**Comment by lizyChy0329** [comment]
So cool! Have a good time!

Thank you for creating so wonderful stuff, I will keep on overwatching this library!
